# Generated by Django 4.2.14 on 2025-07-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialrent',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
